//
// Created by lukasz on 12.11.25.
//

#ifndef DIJKSTRA_MULTITHREADED_SRC_DIJKSTRA_ALGORITHM_INCLUDE_DIJKSTRA_ALGORITHM_EDGE_HPP_
#define DIJKSTRA_MULTITHREADED_SRC_DIJKSTRA_ALGORITHM_INCLUDE_DIJKSTRA_ALGORITHM_EDGE_HPP_

namespace dijkstra_algorithm {

struct Edge {
  int to, weight;
};

}

#endif //DIJKSTRA_MULTITHREADED_SRC_DIJKSTRA_ALGORITHM_INCLUDE_DIJKSTRA_ALGORITHM_EDGE_HPP_
