//
// Created by lukasz on 25.11.25.
//

#ifndef DIJKSTRA_MULTITHREADED_SRC_GRAPH_GENERATOR_INCLUDE_GRAPH_GENERATOR_GRAPH_GENERATOR_HPP_
#define DIJKSTRA_MULTITHREADED_SRC_GRAPH_GENERATOR_INCLUDE_GRAPH_GENERATOR_GRAPH_GENERATOR_HPP_

#include <data_structures/graph.hpp>
Graph generate_random_graph(int n, int m, double max_w = 10.0);

#endif //DIJKSTRA_MULTITHREADED_SRC_GRAPH_GENERATOR_INCLUDE_GRAPH_GENERATOR_GRAPH_GENERATOR_HPP_
